apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fineractreportUI.fullname" . }}
  labels:
    app: finearct-report-ui
spec:
  selector:
    matchLabels:
      app: finearct-report-ui
      tier: frontend
  replicas: {{ .Values.fineractreportUI.replicaCount }}
  template:
    metadata:
      labels:
        app: finearct-report-ui
        tier: frontend
    spec:
      containers:
        - name: finearct-report-ui
          image: "{{ .Values.fineract_frontend.image.name }}:{{ .Values.fineract_frontend.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy}}
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
          - name: FINERACT_DOMAIN
            value: {{ .Values.commonconfig.FINERACT_REPORT_DOMAIN }}
          - name: FINERACT_BASE_URL
            value: {{ .Values.commonconfig.FINERACT_BASE_URL }}
          - name: FINERACT_PROXY_URL
            value: "https://{{ template "fineract.report.fullname" . }}:8443"
          - name: DOLLAR
            value: $
          args:
            - /bin/bash
            - -c
            - envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            {{- .Values.fineractreportUI.resources | toYaml | nindent 12 }}