apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fineract.job.fullname" . }}
  labels:
    app: fineract-job
spec:
  selector:
    matchLabels:
      app: fineract-job
      tier: middle
  replicas: {{ .Values.fineractjob.replicaCount }}
  serviceName: fineract-job
  template:
    metadata:
      labels:
        app: fineract-job
        tier: middle
    spec:
      containers:
        - name: fineract-job
          image: "{{ .Values.fineract_backend.image.name }}:{{ .Values.fineract_backend.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy}}
          ports:
            - name: job-port
              containerPort: 8443
          env:
            - name: FINERACT_DEFAULT_TENANTDB_HOSTNAME
              value: {{ include "mysql_host" . }}
            - name: FINERACT_DEFAULT_TENANTDB_UID
              value: {{ include "mysql_user" . }}
            - name: FINERACT_DEFAULT_TENANTDB_PWD
              value: {{ .Values.mysql.auth.password }}
            - name: fineract_tenants_uid
              value: {{ include "mysql_user" . }}
            - name: fineract_tenants_pwd
              value: {{ .Values.mysql.auth.password }}
            - name: fineract_tenants_url
              value: "jdbc:mysql://{{ include "mysql_host" . }}:3306/{{ .Values.global.db.tenantsDb }}"
            - name: FINERACT_DEFAULT_TENANTDB_PORT
              value: "{{ .Values.commonconfig.FINERACT_DEFAULT_TENANTDB_PORT }}"
            - name: fineract.allowJobs
              value: "true"
            - name: brokerUrl
              value: {{ .Values.commonconfig.brokerUrl }}
          args:
            - sh
            - -c
            - java -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true --illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED -jar fineract-provider.jar --spring.profiles.active=basicauth,activeMqEnabled
          livenessProbe:
            tcpSocket:
              port: job-port
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: job-port
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
          volumeMounts:
            - name: fineract-job
              mountPath: /opt/fineract/logs
          resources:
            {{- .Values.fineractjob.resources | toYaml | nindent 12 }}
      volumes:
        - name: fineract-job
          persistentVolumeClaim:
            claimName: fineract-job-pvc
