apiVersion: v1
kind: Service
metadata:
  name: {{ template "fineractreportUI.fullname" . }}
  labels:
    app: finearct-report-ui
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
  selector:
    app: finearct-report-ui
    tier: frontend
