kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  FINERACT_DEFAULT_TENANTDB_HOSTNAME: {{ default "" .Values.fineract_db.HOSTNAME | b64enc | quote }}
  FINERACT_DEFAULT_TENANTDB_UID: {{ default "" .Values.fineract_db.USERNAME | b64enc | quote }}
  FINERACT_DEFAULT_TENANTDB_PWD: {{ default "" .Values.fineract_db.PASSWORD | b64enc | quote }}
type: Opaque