fineract_backend:
  image:
    name: "941647722717.dkr.ecr.eu-west-1.amazonaws.com/fineract-vfd"
    tag: "vikas"

fineract_frontend:
  image:
    name: "941647722717.dkr.ecr.eu-west-1.amazonaws.com/vfd-frontend"
    tag: "vikas-com"

mysql:
  auth:
    password: "user-ddef-aqw"
    rootPassword: "tjgu-Xdef-aqw"

commonconfig:
    FINERACT_REST_DOMAIN: "localhost"

ingress:
  enabled: true

storageClassName: "aws-efs"
accessModes: "ReadWriteMany"
