apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fineract-report-pvc
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
