fineract_backend:
  image:
    # Fineract backend image name
    name: ""
    # Fineract backend image tag
    tag: ""

# Settings for Fineract job backend microservice
fineractjob:
  name: fineractjob
  # Number of Fineract job pods
  replicaCount: 1
  # Resource settings for Fineract job backend pods
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Settings for Fineract report backend microservice
fineractreport:
  name: fineractreport
  # Number of Fineract report pods
  replicaCount: 1
  # Resource settings for Fineract report backend pods
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Settings for Fineract rest backend microservice
fineractrest:
  name: fineractrest
  # Number of Fineract rest pods
  replicaCount: 1
  # Resource settings for Fineract rest backend pods
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"

fineract_frontend:
  image:
    # Fineract frontend image name
    name: ""
    # Fineract frontend image tag
    tag: ""

# Settings for Fineract rest frontend microservice
fineractrestUI:
  name: fineractrestui
  # Number of Fineract rest UI pods
  replicaCount: 1
  # Resource settings for Fineract rest UI pods
  resources:
    limits:
      cpu: "100m"
      memory: "100Mi"

# Settings for Fineract job frontend microservice
fineractjobUI:
  name: fineractjobui
  # Number of Fineract job UI pods
  replicaCount: 1
  # Resource settings for Fineract job UI pods
  resources:
    limits:
      cpu: "100m"
      memory: "100Mi"

# Settings for Fineract report frontend microservice
fineractreportUI:
  name: fineractreportui
  # Number of Fineract report UI pods
  replicaCount: 1
  # Resource settings for Fineract report UI pods
  resources:
    limits:
      cpu: "100m"
      memory: "100Mi"

commonconfig:
  brokerUrl: tcp://fineract-activemq-svc:61616
  FINERACT_BASE_URL: /fineract-provider/api/v1
  # Domain name for Fineract rest UI
  FINERACT_REST_DOMAIN: fineract-rest.oneacrefund.org
  # Domain name for Fineract job UI
  FINERACT_JOB_DOMAIN: fineract-job.oneacrefund.org
  # Domain name for Fineract report UI
  FINERACT_REPORT_DOMAIN: fineract-report.oneacrefund.org

fineract_db:
  #  DB hostname
  HOSTNAME: ""
  #  DB username
  USERNAME: ""
  #  DB password
  PASSWORD: ""
  #  DB name for tenants db
  FINERACT_DEFAULT_TENANTDB_NAME: fineract_tenants
  FINERACT_DEFAULT_TENANTDB_PORT: 3306

fineractactivemq:
  name: activemq
  # Activemq image
  image: "webcenter/activemq:5.14.3"
  # Number of activemq pods
  replicaCount: 1

fineractactivemqconfig:
  ACTIVEMQ_MIN_MEMORY: "512"
  ACTIVEMQ_MAX_MEMORY: "1024"

# StorageClass name for PVC
storageClassName: aws-efs
imagePullPolicy: "Always"
