apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: mautic
version: 0.1.0
dependencies:
  - name: mariadb
    version: ~11.4.6
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
